name: Archibus-Automated-Scheduler

on:
    workflow_dispatch:
    schedule:
      - cron: "0 9 * * 1,3,5"  # Runs at 9:00 AM UTC on Monday, Wednesday, and Friday
    
jobs:
  archibus-automated-scheduler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.X

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: python-archibus-scheduler
      run: |
        python src/main.py ${{ secrets.archibus_scheduling_args }}
