name: Archibus-Automated-Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1,3,5"

jobs:
  archibus-automated-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./
        with:
          scheduling_args: ${{ secrets.ARCHIBUS_SCHEDULING_ARGS }}